# Sample .travis.yml for R projects

language: r
cache: packages
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
sudo: required

apt_packages:
  - libudunits2-dev 
  - libproj-dev 
  - libgeos-dev 
  - libgdal-dev

r_binary_packages:
 - rgdal
 - rgeos

r_packages:
  - devtools

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
# r_github_packages:
#  - beanumber/etl
